<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- The sample app is not a NuGet package. -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SimpleFlux\SimpleFlux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Faker.Net" Version="2.0.163" />
  </ItemGroup>

</Project>
