<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\SimpleFlux\SimpleFlux.csproj" />
    <ProjectReference Include="..\src\SimpleFlux.AzureTables\SimpleFlux.AzureTables.csproj" />
    <ProjectReference Include="..\src\SimpleFlux.InMemory\SimpleFlux.InMemory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
