name: SimpleFlux-main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

    steps:
    
    - name: Echo build number
      shell: bash
      run: |
        echo "BuildNumber1: ${{ vars.BUILD_NUMBER }}"
  
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      run: dotnet pack --no-restore --configuration Release --output .

    - name: Publish
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
