name: SimpleFlux-main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Current version number
      shell: bash
      run: |
        echo "Last Build Number: ${{ vars.BUILD_NUMBER_PREFIX }}.${{ vars.BUILD_NUMBER_PATCH }}"
  
    - name: Next patch number
      shell: bash
      run: |
        echo "Next Patch: $((${{ vars.BUILD_NUMBER_PATCH }}+1))"
  
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      run: dotnet pack --no-restore --configuration Release --output .

    - name: Publish
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
