name: SimpleFlux-main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Echo build number
      shell: bash
      run: |
        echo "BuildNumber: $BUILD_NUMBER"

    - uses: action-pack/set-variable@v1
      with:
        name: 'BuildNumber'
        value: '1.0.0'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      run: dotnet pack --no-restore --configuration Release --output .

    - name: Publish
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
